### ISSUE TITLE
Consider support `minitest-reporters` added `Minitest::Reporters::DelegateReporter`

### ISSUE THREAD

**Issue by dr-js** [jeremyevans/minitest-parallel_fork#8]
For our Rails test setup we added `minitest-reporters` gem,
when combined with `minitest-parallel_fork`,
all test code will pass,
but in the end there's error for each fork like:
```
Traceback (most recent call last):
        8: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:68:in `block in autorun'
        7: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:141:in `run'
        6: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-parallel_fork-1.2.0/lib/minitest/parallel_fork.rb:43:in `__run'
        5: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-parallel_fork-1.2.0/lib/minitest/parallel_fork.rb:43:in `times'
        4: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-parallel_fork-1.2.0/lib/minitest/parallel_fork.rb:46:in `block in __run'
        3: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-parallel_fork-1.2.0/lib/minitest/parallel_fork.rb:46:in `fork'
        2: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-parallel_fork-1.2.0/lib/minitest/parallel_fork.rb:62:in `block (2 levels) in __run'
        1: from /app/vendor/bundle/ruby/2.7.0/gems/minitest-parallel_fork-1.2.0/lib/minitest/parallel_fork.rb:62:in `map'
/app/vendor/bundle/ruby/2.7.0/gems/minitest-parallel_fork-1.2.0/lib/minitest/parallel_fork.rb:62:in `block (3 levels) in __run': undefined method `count' for nil:NilClass (NoMethodError)
```

The reason is `stat_reporter` become `nil`

Compare the code: [parallel_fork.rb#L27](https://github.com/jeremyevans/minitest-parallel_fork/blob/1.2.0/lib/minitest/parallel_fork.rb#L27)
```ruby
  def self.parallel_fork_stat_reporter(reporter)
    reporter.reporters.detect{|rep| rep.is_a?(StatisticsReporter)}
  end
```
and actual `pp reporter.reporters` output in our case looks like:
```
[#<Minitest::Reporters::DelegateReporter:0x00007f8f1dd42930
  @all_reporters=
   [#<Minitest::SummaryReporter:0x00007f8f1dd42ae8
     @_mutex=#<Thread::Mutex:0x00007f8f1dd42a98>,
     @assertions=0,
     @count=0,
     ...>,
    #<Minitest::ProgressReporter:0x00007f8f1dd42a48
     @_mutex=#<Thread::Mutex:0x00007f8f1dd429f8>,
     @io=#<IO:<STDOUT>>,
     ...>],
  @options=
   {:io=>#<IO:<STDOUT>>,
    :color=>true,
    :output_inline=>true,
    :seed=>19915,
    :args=>"--seed 19915"},
  @reporters=
   [#<Minitest::SummaryReporter:0x00007f8f1dd42ae8
     @_mutex=#<Thread::Mutex:0x00007f8f1dd42a98>,
     @assertions=0,
     @count=0,
     ...>,
    #<Minitest::ProgressReporter:0x00007f8f1dd42a48
     @_mutex=#<Thread::Mutex:0x00007f8f1dd429f8>,
     @io=#<IO:<STDOUT>>,
     ...>]>]
```

The `Minitest::Reporters::DelegateReporter` is added by `minitest-reporters`

For now we just removed `minitest-reporters` from our `Gemfile`,
and the test will pass without error.

**Comment by joshheinrichs-shopify** [comment]
i don't think this works with `DelegateReporter` as it doesn't respond to `count assertions results count= assertions=`. i'm not sure this is really fixable without adjustments in minitest-reporters, as [`DelegateReporter` also doesn't let you get at its reporters](https://github.com/minitest-reporters/minitest-reporters/blob/265ff4b40d5827e84d7e902b808fbee860b61221/lib/minitest/minitest_reporter_plugin.rb), so you can't recursively dig through things that respond to `reporters` 😕

**Comment by jeremyevans** [comment]
That's unfortunate.  Do you have a suggestion for supporting what you want without adding a dependency?  Could you add a custom reporter that responds to those methods and also uses `DelegateReporter`?
